import type { Region, Team, User, Customer, Proposal, Deal, Notification, InventoryItem, ProposalLineItem, ProposalVersion } from '@/types';

export const seedRegions: Region[] = [
  { id: 'r1', name: 'North' },
  { id: 'r2', name: 'West' },
  { id: 'r3', name: 'South' },
  { id: 'r4', name: 'East' },
];

export const seedTeams: Team[] = [
  { id: 't1', name: 'West - Team A', regionId: 'r2' },
  { id: 't2', name: 'West - Team B', regionId: 'r2' },
  { id: 't3', name: 'North - Team A', regionId: 'r1' },
];

export const seedUsers: User[] = [
  { id: 'u1', name: 'Mohit (Admin)', email: 'mohit@buildesk.com', password: 'admin123', role: 'super_admin', teamId: 't1', regionId: 'r2', status: 'active' },
  { id: 'u2', name: 'Neha (Finance)', email: 'neha@buildesk.com', password: 'finance123', role: 'finance', teamId: 't1', regionId: 'r2', status: 'active' },
  { id: 'u3', name: 'Ravi (Sales Manager)', email: 'ravi@buildesk.com', password: 'manager123', role: 'sales_manager', teamId: 't1', regionId: 'r2', status: 'active' },
  { id: 'u4', name: 'Amit (Sales Rep)', email: 'amit@buildesk.com', password: 'sales123', role: 'sales_rep', teamId: 't1', regionId: 'r2', status: 'active' },
  { id: 'u5', name: 'Sana (Sales Rep)', email: 'sana@buildesk.com', password: 'sales123', role: 'sales_rep', teamId: 't2', regionId: 'r2', status: 'active' },
  { id: 'u6', name: 'Kiran (Support)', email: 'kiran@buildesk.com', password: 'support123', role: 'support', teamId: 't3', regionId: 'r1', status: 'active' },
];

export const seedCustomers: Customer[] = [
  {
    id: 'c1',
    leadId: 'L-0001',
    name: 'Sunrise Developers',
    state: 'Maharashtra',
    gstin: '27ABCDE1234F1Z5',
    regionId: 'r2',
    city: 'Mumbai',
    email: 'contact@sunrise.dev',
    primaryPhone: '+91 90000 00001',
    status: 'active',
    createdAt: '2026-03-01T10:00:00Z',
    salesExecutive: 'Amit (Sales Rep)',
    accountManager: 'Ravi (Sales Manager)',
    deliveryExecutive: 'Anurag',
  },
  {
    id: 'c2',
    leadId: 'L-0002',
    name: 'Greenfield Realty',
    state: 'Gujarat',
    gstin: null,
    regionId: 'r2',
    city: 'Ahmedabad',
    email: 'info@greenfieldrealty.in',
    primaryPhone: '+91 90000 00002',
    status: 'active',
    createdAt: '2026-03-05T11:30:00Z',
    salesExecutive: 'Sana (Sales Rep)',
    accountManager: 'Ravi (Sales Manager)',
    deliveryExecutive: 'Anurag',
  },
  {
    id: 'c3',
    leadId: 'L-0003',
    name: 'NorthStar Builders',
    state: 'Delhi',
    gstin: '07ABCDE1234F1Z5',
    regionId: 'r1',
    city: 'New Delhi',
    email: 'sales@northstar.dev',
    primaryPhone: '+91 90000 00003',
    status: 'inactive',
    createdAt: '2026-02-20T09:15:00Z',
    salesExecutive: 'Amit (Sales Rep)',
    accountManager: 'Ravi (Sales Manager)',
    deliveryExecutive: 'Kiran',
  },
];

function makeLineItem(
  id: string,
  invId: string,
  name: string,
  sku: string,
  qty: number,
  unitPrice: number,
  taxRate: number,
  discount = 0
): ProposalLineItem {
  const lineTotal = qty * unitPrice * (1 - discount / 100);
  const taxAmount = (lineTotal * taxRate) / 100;
  return { id, inventoryItemId: invId, name, sku, qty, unitPrice, taxRate, discount, lineTotal, taxAmount };
}

const pNow = '2026-03-12T10:00:00Z';
function pVersions(lineItems: ProposalLineItem[], subtotal: number, totalDiscount: number, totalTax: number, grandTotal: number): ProposalVersion[] {
  return [{ version: 1, createdAt: pNow, createdBy: 'u4', lineItems, subtotal, totalDiscount, totalTax, grandTotal }];
}

export const seedProposals: Proposal[] = [
  {
    id: 'p1',
    proposalNumber: 'PROP-2026-0041',
    title: 'Enterprise CRM + Analytics Bundle',
    customerId: 'c1',
    customerName: 'Sunrise Developers',
    assignedTo: 'u4',
    assignedToName: 'Amit (Sales Rep)',
    regionId: 'r2',
    teamId: 't1',
    status: 'sent',
    validUntil: '2026-04-15',
    lineItems: [
      makeLineItem('li1', 'inv1', 'Buildesk CRM Pro', 'CRM-PRO-001', 10, 15000, 18),
      makeLineItem('li2', 'inv3', 'Analytics Add-on Annual', 'SUB-ANAL-ANN', 1, 42000, 18),
    ],
    subtotal: 192000,
    totalDiscount: 0,
    totalTax: 34560,
    grandTotal: 226560,
    finalQuoteValue: 222000,
    versionHistory: pVersions(
      [makeLineItem('li1', 'inv1', 'Buildesk CRM Pro', 'CRM-PRO-001', 10, 15000, 18), makeLineItem('li2', 'inv3', 'Analytics Add-on Annual', 'SUB-ANAL-ANN', 1, 42000, 18)],
      192000, 0, 34560, 226560
    ),
    currentVersion: 1,
    customerNotes: 'Thank you for your business.',
    createdAt: '2026-03-08T10:00:00Z',
    updatedAt: '2026-03-10T14:00:00Z',
    createdBy: 'u4',
    approvedBy: 'u3',
    approvedAt: '2026-03-10T14:30:00Z',
    sentAt: '2026-03-10T15:00:00Z',
  },
  {
    id: 'p2',
    proposalNumber: 'PROP-2026-0042',
    title: 'ERP Implementation & Support',
    customerId: 'c2',
    customerName: 'Greenfield Realty',
    assignedTo: 'u5',
    assignedToName: 'Sana (Sales Rep)',
    regionId: 'r2',
    teamId: 't2',
    status: 'approval_pending',
    validUntil: '2026-04-20',
    lineItems: [
      makeLineItem('li3', 'inv2', 'ERP Integration Service', 'SVC-ERP-001', 40, 2500, 18),
      makeLineItem('li4', 'inv5', 'Support & AMC Monthly', 'SUB-AMC-MON', 12, 5500, 18),
    ],
    subtotal: 166000,
    totalDiscount: 0,
    totalTax: 29880,
    grandTotal: 195880,
    versionHistory: pVersions(
      [makeLineItem('li3', 'inv2', 'ERP Integration Service', 'SVC-ERP-001', 40, 2500, 18), makeLineItem('li4', 'inv5', 'Support & AMC Monthly', 'SUB-AMC-MON', 12, 5500, 18)],
      166000, 0, 29880, 195880
    ),
    currentVersion: 1,
    createdAt: '2026-03-11T09:00:00Z',
    updatedAt: '2026-03-12T11:00:00Z',
    createdBy: 'u5',
  },
  {
    id: 'p3',
    proposalNumber: 'PROP-2026-0043',
    title: 'Full Stack License Deal',
    customerId: 'c1',
    customerName: 'Sunrise Developers',
    assignedTo: 'u4',
    assignedToName: 'Amit (Sales Rep)',
    regionId: 'r2',
    teamId: 't1',
    status: 'approved',
    validUntil: '2026-04-30',
    lineItems: [makeLineItem('li5', 'inv4', 'Enterprise Bundle', 'BND-ENT-001', 1, 320000, 18, 5)],
    subtotal: 304000,
    totalDiscount: 16000,
    totalTax: 54720,
    grandTotal: 342720,
    versionHistory: pVersions(
      [makeLineItem('li5', 'inv4', 'Enterprise Bundle', 'BND-ENT-001', 1, 320000, 18, 5)],
      304000, 16000, 54720, 342720
    ),
    currentVersion: 1,
    approvedBy: 'u3',
    approvedAt: '2026-03-13T10:00:00Z',
    createdAt: '2026-03-12T14:00:00Z',
    updatedAt: '2026-03-13T10:00:00Z',
    createdBy: 'u4',
  },
  {
    id: 'p4',
    proposalNumber: 'PROP-2026-0044',
    title: 'CRM Lite Pilot',
    customerId: 'c3',
    customerName: 'NorthStar Builders',
    assignedTo: 'u4',
    assignedToName: 'Amit (Sales Rep)',
    regionId: 'r1',
    teamId: 't3',
    status: 'draft',
    validUntil: '2026-05-01',
    lineItems: [makeLineItem('li6', 'inv1', 'Buildesk CRM Pro', 'CRM-PRO-001', 5, 15000, 18)],
    subtotal: 75000,
    totalDiscount: 0,
    totalTax: 13500,
    grandTotal: 88500,
    versionHistory: pVersions([makeLineItem('li6', 'inv1', 'Buildesk CRM Pro', 'CRM-PRO-001', 5, 15000, 18)], 75000, 0, 13500, 88500),
    currentVersion: 1,
    createdAt: '2026-03-13T09:00:00Z',
    updatedAt: '2026-03-13T09:00:00Z',
    createdBy: 'u4',
  },
  {
    id: 'p5',
    proposalNumber: 'PROP-2026-0045',
    title: 'Implementation Pack Only',
    customerId: 'c2',
    customerName: 'Greenfield Realty',
    assignedTo: 'u5',
    assignedToName: 'Sana (Sales Rep)',
    regionId: 'r2',
    teamId: 't2',
    status: 'rejected',
    validUntil: '2026-04-10',
    lineItems: [makeLineItem('li7', 'inv6', 'Implementation Services Pack', 'SVC-IMPL-001', 1, 75000, 18)],
    subtotal: 75000,
    totalDiscount: 0,
    totalTax: 13500,
    grandTotal: 88500,
    rejectionReason: 'Budget approved for next quarter. Please resubmit in April.',
    versionHistory: pVersions([makeLineItem('li7', 'inv6', 'Implementation Services Pack', 'SVC-IMPL-001', 1, 75000, 18)], 75000, 0, 13500, 88500),
    currentVersion: 1,
    createdAt: '2026-03-10T11:00:00Z',
    updatedAt: '2026-03-11T16:00:00Z',
    createdBy: 'u5',
  },
  {
    id: 'p6',
    proposalNumber: 'PROP-2026-0046',
    title: 'Annual Renewal - Sunrise',
    customerId: 'c1',
    customerName: 'Sunrise Developers',
    assignedTo: 'u4',
    assignedToName: 'Amit (Sales Rep)',
    regionId: 'r2',
    teamId: 't1',
    status: 'deal_created',
    validUntil: '2026-04-25',
    lineItems: [
      makeLineItem('li8', 'inv1', 'Buildesk CRM Pro', 'CRM-PRO-001', 20, 14500, 18, 3),
      makeLineItem('li9', 'inv5', 'Support & AMC Monthly', 'SUB-AMC-MON', 12, 5000, 18),
    ],
    subtotal: 340000,
    totalDiscount: 10200,
    totalTax: 59364,
    grandTotal: 389164,
    finalQuoteValue: 385000,
    dealId: 'd1',
    versionHistory: pVersions(
      [makeLineItem('li8', 'inv1', 'Buildesk CRM Pro', 'CRM-PRO-001', 20, 14500, 18, 3), makeLineItem('li9', 'inv5', 'Support & AMC Monthly', 'SUB-AMC-MON', 12, 5000, 18)],
      340000, 10200, 59364, 389164
    ),
    currentVersion: 1,
    approvedBy: 'u3',
    approvedAt: '2026-03-09T12:00:00Z',
    sentAt: '2026-03-09T14:00:00Z',
    createdAt: '2026-03-08T08:00:00Z',
    updatedAt: '2026-03-09T15:00:00Z',
    createdBy: 'u4',
  },
];

export const seedDeals: Deal[] = [
  { id: 'd1', name: 'CRM+ERP Renewal 2026', customerId: 'c1', ownerUserId: 'u4', teamId: 't1', regionId: 'r2', stage: 'Negotiation', value: 385000, locked: true, proposalId: 'p6' },
  { id: 'd2', name: 'New Implementation', customerId: 'c2', ownerUserId: 'u5', teamId: 't2', regionId: 'r2', stage: 'Qualified', value: 220000, locked: false, proposalId: null },
];

export const seedNotifications: Notification[] = [
  { id: 'n1', type: 'CUSTOMER_EMAIL', to: 'accounts@sunrise.dev', subject: 'Buildesk Proposal PROP-2026-0007 shared', entityId: 'p1', at: '2026-03-10T15:00:00Z' },
  { id: 'n2', type: 'INTERNAL_EMAIL', to: 'admin@buildesk.com', subject: 'Final quote value overridden (Sales Manager)', entityId: 'p1', at: '2026-03-10T14:35:00Z' },
];

const seedNow = '2026-03-01T10:00:00Z';
export const seedInventoryItems: InventoryItem[] = [
  {
    id: 'inv1',
    name: 'Buildesk CRM Pro',
    description: 'Full CRM suite with contacts, pipeline, and reporting',
    itemType: 'product',
    sku: 'CRM-PRO-001',
    hsnSacCode: '998314',
    category: 'CRM Suite',
    unitOfMeasure: 'per license',
    costPrice: 8000,
    sellingPrice: 15000,
    taxRate: 18,
    isActive: true,
    createdAt: seedNow,
    updatedAt: seedNow,
    createdBy: 'u1',
    notes: 'Flagship product',
  },
  {
    id: 'inv2',
    name: 'ERP Integration Service',
    description: 'One-time implementation and integration with existing ERP',
    itemType: 'service',
    sku: 'SVC-ERP-001',
    hsnSacCode: '998313',
    category: 'ERP Platform',
    unitOfMeasure: 'per hour',
    costPrice: 1200,
    sellingPrice: 2500,
    taxRate: 18,
    isActive: true,
    createdAt: seedNow,
    updatedAt: seedNow,
    createdBy: 'u1',
  },
  {
    id: 'inv3',
    name: 'Analytics Add-on Annual',
    description: 'Advanced analytics and BI dashboards',
    itemType: 'subscription',
    sku: 'SUB-ANAL-ANN',
    hsnSacCode: '998314',
    category: 'Analytics Add-on',
    unitOfMeasure: 'per year',
    costPrice: 24000,
    sellingPrice: 42000,
    taxRate: 18,
    isActive: true,
    createdAt: seedNow,
    updatedAt: seedNow,
    createdBy: 'u1',
  },
  {
    id: 'inv4',
    name: 'Enterprise Bundle',
    description: 'CRM + ERP + Analytics, annual commitment',
    itemType: 'bundle',
    sku: 'BND-ENT-001',
    hsnSacCode: '998314',
    category: 'CRM Suite',
    unitOfMeasure: 'per year',
    costPrice: 180000,
    sellingPrice: 320000,
    taxRate: 18,
    isActive: true,
    createdAt: seedNow,
    updatedAt: seedNow,
    createdBy: 'u1',
  },
  {
    id: 'inv5',
    name: 'Support & AMC Monthly',
    description: 'Monthly support and annual maintenance contract',
    itemType: 'subscription',
    sku: 'SUB-AMC-MON',
    hsnSacCode: '998313',
    category: 'Support & AMC',
    unitOfMeasure: 'per month',
    costPrice: 3000,
    sellingPrice: 5500,
    taxRate: 18,
    isActive: true,
    createdAt: seedNow,
    updatedAt: seedNow,
    createdBy: 'u1',
  },
  {
    id: 'inv6',
    name: 'Implementation Services Pack',
    description: 'On-site implementation and training',
    itemType: 'service',
    sku: 'SVC-IMPL-001',
    hsnSacCode: '998313',
    category: 'Implementation Services',
    unitOfMeasure: 'per unit',
    costPrice: 45000,
    sellingPrice: 75000,
    taxRate: 18,
    isActive: true,
    createdAt: seedNow,
    updatedAt: seedNow,
    createdBy: 'u1',
  },
  {
    id: 'inv7',
    name: 'Storage Add-on (per GB)',
    description: 'Additional cloud storage per GB per month',
    itemType: 'subscription',
    sku: 'SUB-STOR-GB',
    hsnSacCode: '998314',
    category: 'Analytics Add-on',
    unitOfMeasure: 'per GB',
    costPrice: 2,
    sellingPrice: 5,
    taxRate: 18,
    isActive: true,
    createdAt: seedNow,
    updatedAt: seedNow,
    createdBy: 'u1',
  },
  {
    id: 'inv8',
    name: 'Legacy CRM Lite (Discontinued)',
    description: 'Legacy lite version - no new sales',
    itemType: 'product',
    sku: 'CRM-LITE-OLD',
    hsnSacCode: '998314',
    category: 'CRM Suite',
    unitOfMeasure: 'per license',
    costPrice: 2000,
    sellingPrice: 3500,
    taxRate: 18,
    isActive: false,
    createdAt: seedNow,
    updatedAt: seedNow,
    createdBy: 'u1',
    notes: 'Discontinued',
  },
];
