/**
 * Country list for phone input (ISO code + E.164 dial code).
 * Sorted with India first for Buildesk; then alphabetical by name.
 */
export const countries: { name: string; iso: string; code: string }[] = [
  { name: "India", iso: "IN", code: "+91" },
  { name: "United States", iso: "US", code: "+1" },
  { name: "United Kingdom", iso: "GB", code: "+44" },
  { name: "Australia", iso: "AU", code: "+61" },
  { name: "Canada", iso: "CA", code: "+1" },
  { name: "Germany", iso: "DE", code: "+49" },
  { name: "France", iso: "FR", code: "+33" },
  { name: "Singapore", iso: "SG", code: "+65" },
  { name: "United Arab Emirates", iso: "AE", code: "+971" },
  { name: "Saudi Arabia", iso: "SA", code: "+966" },
  { name: "Pakistan", iso: "PK", code: "+92" },
  { name: "Bangladesh", iso: "BD", code: "+880" },
  { name: "Sri Lanka", iso: "LK", code: "+94" },
  { name: "Nepal", iso: "NP", code: "+977" },
  { name: "Afghanistan", iso: "AF", code: "+93" },
  { name: "Indonesia", iso: "ID", code: "+62" },
  { name: "Malaysia", iso: "MY", code: "+60" },
  { name: "Philippines", iso: "PH", code: "+63" },
  { name: "Thailand", iso: "TH", code: "+66" },
  { name: "Vietnam", iso: "VN", code: "+84" },
  { name: "China", iso: "CN", code: "+86" },
  { name: "Japan", iso: "JP", code: "+81" },
  { name: "South Korea", iso: "KR", code: "+82" },
  { name: "Hong Kong", iso: "HK", code: "+852" },
  { name: "New Zealand", iso: "NZ", code: "+64" },
  { name: "South Africa", iso: "ZA", code: "+27" },
  { name: "Nigeria", iso: "NG", code: "+234" },
  { name: "Kenya", iso: "KE", code: "+254" },
  { name: "Egypt", iso: "EG", code: "+20" },
  { name: "Brazil", iso: "BR", code: "+55" },
  { name: "Mexico", iso: "MX", code: "+52" },
  { name: "Argentina", iso: "AR", code: "+54" },
  { name: "Colombia", iso: "CO", code: "+57" },
  { name: "Chile", iso: "CL", code: "+56" },
  { name: "Netherlands", iso: "NL", code: "+31" },
  { name: "Spain", iso: "ES", code: "+34" },
  { name: "Italy", iso: "IT", code: "+39" },
  { name: "Sweden", iso: "SE", code: "+46" },
  { name: "Poland", iso: "PL", code: "+48" },
  { name: "Belgium", iso: "BE", code: "+32" },
  { name: "Switzerland", iso: "CH", code: "+41" },
  { name: "Austria", iso: "AT", code: "+43" },
  { name: "Ireland", iso: "IE", code: "+353" },
  { name: "Portugal", iso: "PT", code: "+351" },
  { name: "Russia", iso: "RU", code: "+7" },
  { name: "Turkey", iso: "TR", code: "+90" },
  { name: "Israel", iso: "IL", code: "+972" },
  { name: "Iran", iso: "IR", code: "+98" },
  { name: "Iraq", iso: "IQ", code: "+964" },
  { name: "Kuwait", iso: "KW", code: "+965" },
  { name: "Qatar", iso: "QA", code: "+974" },
  { name: "Bahrain", iso: "BH", code: "+973" },
  { name: "Oman", iso: "OM", code: "+968" },
  { name: "Jordan", iso: "JO", code: "+962" },
  { name: "Lebanon", iso: "LB", code: "+961" },
  { name: "Ghana", iso: "GH", code: "+233" },
  { name: "Ethiopia", iso: "ET", code: "+251" },
  { name: "Tanzania", iso: "TZ", code: "+255" },
  { name: "Uganda", iso: "UG", code: "+256" },
  { name: "Morocco", iso: "MA", code: "+212" },
  { name: "Algeria", iso: "DZ", code: "+213" },
  { name: "Tunisia", iso: "TN", code: "+216" },
  { name: "Ukraine", iso: "UA", code: "+380" },
  { name: "Czech Republic", iso: "CZ", code: "+420" },
  { name: "Romania", iso: "RO", code: "+40" },
  { name: "Hungary", iso: "HU", code: "+36" },
  { name: "Greece", iso: "GR", code: "+30" },
  { name: "Denmark", iso: "DK", code: "+45" },
  { name: "Norway", iso: "NO", code: "+47" },
  { name: "Finland", iso: "FI", code: "+358" },
  { name: "Peru", iso: "PE", code: "+51" },
  { name: "Venezuela", iso: "VE", code: "+58" },
  { name: "Ecuador", iso: "EC", code: "+593" },
  { name: "Other", iso: "XX", code: "+00" },
];
